// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SecretsClient.Infrastructure.Data;

#nullable disable

namespace SecretsClient.Infrastructure.Migrations
{
    [DbContext(typeof(SecretsDbContext))]
    partial class SecretsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("SecretsClient.Core.Domain.Entities.GeoPolicy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<double>("RadiusMeters")
                        .HasColumnType("REAL");

                    b.Property<Guid>("SecretId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SecretId");

                    b.ToTable("GeoPolicies");
                });

            modelBuilder.Entity("SecretsClient.Core.Domain.Entities.Secret", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("EncryptedPayload")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EncryptionAlgorithm")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Secrets");
                });

            modelBuilder.Entity("SecretsClient.Core.Domain.Entities.SecretFragment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("EncryptedFragment")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FragmentChecksum")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("FragmentIndex")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SecretId")
                        .HasColumnType("TEXT");

                    b.Property<string>("StorageLocation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SecretId");

                    b.ToTable("Fragments");
                });

            modelBuilder.Entity("SecretsClient.Core.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PublicKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SecretsClient.Core.Domain.Entities.GeoPolicy", b =>
                {
                    b.HasOne("SecretsClient.Core.Domain.Entities.Secret", null)
                        .WithMany("GeoPolicies")
                        .HasForeignKey("SecretId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SecretsClient.Core.Domain.Entities.Secret", b =>
                {
                    b.HasOne("SecretsClient.Core.Domain.Entities.User", null)
                        .WithMany("Secrets")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SecretsClient.Core.Domain.Entities.SecretFragment", b =>
                {
                    b.HasOne("SecretsClient.Core.Domain.Entities.Secret", null)
                        .WithMany("Fragments")
                        .HasForeignKey("SecretId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SecretsClient.Core.Domain.Entities.Secret", b =>
                {
                    b.Navigation("Fragments");

                    b.Navigation("GeoPolicies");
                });

            modelBuilder.Entity("SecretsClient.Core.Domain.Entities.User", b =>
                {
                    b.Navigation("Secrets");
                });
#pragma warning restore 612, 618
        }
    }
}
